// add all actions here for cleanliness
const RENDER_DASHBOARD = "RENDER_DASHBOARD";
const RENDER_TRANSACTION = "RENDER_TRANSACTION";
const RENDER_NOTIFICATION = "RENDER_NOTIFICATION";
const RENDER_APP = "RENDER_APP";

export default {
  RENDER_DASHBOARD,
  RENDER_TRANSACTION,
  RENDER_NOTIFICATION,
  RENDER_APP
}
