// add all actions here for cleanliness
const RENDER_DASHBOARD = "RENDER_DASHBOARD";
const RENDER_TRANSACTION = "RENDER_TRANSACTION";
const RENDER_NOTIFICATION = "RENDER_NOTIFICATION";
const RENDER_APP = "RENDER_APP";
const SET_CURRENT_USER = "SET_CURRENT_USER";

export default {
  RENDER_DASHBOARD,
  RENDER_TRANSACTION,
  RENDER_NOTIFICATION,
  RENDER_APP,
  SET_CURRENT_USER
}
