// add all actions here for cleanliness
const RENDER_DASHBOARD = "RENDER_DASHBOARD";
const RENDER_TRANSACTION = "RENDER_TRANSACTION";
const RENDER_NOTIFICATION = "RENDER_NOTIFICATION";

export default {
  RENDER_DASHBOARD,
  RENDER_TRANSACTION,
  RENDER_NOTIFICATION
}
